version: '2'

services:
  nginx-splash:
    image: anthonymejia/nginx-splash
    ports:
      - "80:80"
    environment:
      VIRTUAL_HOST: 'home'
      DEFAULT_HOST: 'home'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  whoami:
    image: jwilder/whoami
    environment:
      VIRTUAL_HOST: 'whoami.test.lan'
      SPLASH_ICON: questions.svg
      SPLASH_NAME: Who Am I
