version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    environment:
      DEFAULT_HOST: 'home.test.lan'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  nginx-splash:
    image: anthonymejia/nginx-splash
    environment:
      VIRTUAL_HOST: 'home.test.lan'
      VIRTUAL_PORT: 80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  whoami:
    image: jwilder/whoami
    environment:
      VIRTUAL_HOST: 'whoami.test.lan'
      SPLASH_ICON: questions.svg
      SPLASH_NAME: Who Am I
